"""
Default detectkit branding for alert channels.

Centralizes the bot identity — display name and avatar — so every channel
defaults to the **detectkit brand**. These are only the fallbacks: each channel
still accepts per-channel overrides (``username`` / ``from_name`` for the name,
``icon_url`` / ``icon_emoji`` for the avatar). Keeping them in one place means
the brand avatar URL and name have a single source of truth.
"""

# Bot display name shown as the message sender across channels (webhook-family
# ``username`` and the email ``From`` display name).
BRAND_USERNAME = "detectkit"

# Brand avatar served from the docs site. Slack/Mattermost render the webhook
# bot icon from a **raster** URL (an SVG is not rendered as a bot avatar), so
# this points at a PNG. Override per channel with ``icon_url`` (a custom image)
# or opt out of the avatar entirely with ``icon_emoji``. The PNG is generated by
# ``website/scripts/make-bot-icon.mjs`` and served from ``website/public/``.
BRAND_ICON_URL = "https://dtk.pipelab.dev/bot-icon.png"
