"""
Default detectkit branding for alert channels.

Centralizes the bot identity — display name and avatar — so every channel
defaults to the **detectkit brand**. These are only the fallbacks: each channel
still accepts per-channel overrides (``username`` / ``from_name`` for the name,
``icon_url`` / ``icon_emoji`` for the avatar). Keeping them in one place means
the brand avatar URL and name have a single source of truth.
"""

# Bot display name shown as the message sender across channels (webhook-family
# ``username`` and the email ``From`` display name).
BRAND_USERNAME = "detectkit"

# Public detectkit site — landing, docs, and the served brand assets. This is the
# **single source of truth** for the project's URL inside the package: the icon
# and alert-guide links below are derived from it, so if the domain ever changes
# only this line needs updating. (Docs/website Markdown and ``pyproject``
# metadata reference the URL directly and are updated in place.)
BRAND_SITE_URL = "https://dtk.pipelab.dev"

# Brand avatar served from the docs site. Slack/Mattermost render the webhook
# bot icon from a **raster** URL (an SVG is not rendered as a bot avatar), so
# this points at a PNG. Override per channel with ``icon_url`` (a custom image)
# or opt out of the avatar entirely with ``icon_emoji``. The PNG is generated by
# ``website/scripts/make-bot-icon.mjs`` and served from ``website/public/``.
BRAND_ICON_URL = f"{BRAND_SITE_URL}/bot-icon.png"

# Default "how to read this alert" link surfaced on every default-rendered alert,
# so non-operator stakeholders (PMs, analysts, on-call) seeing a notification can
# click through to a plain-language guide explaining what they're looking at. It
# points at the official docs page by default; a project can redirect it to its
# own runbook (or hide it) via ``ProjectConfig.alert_help_url`` — the resolved URL
# is stamped onto ``AlertData.help_url`` by the orchestrator. ``ALERT_GUIDE_LABEL``
# is the shared link text so every channel reads the same.
BRAND_ALERT_GUIDE_URL = f"{BRAND_SITE_URL}/guides/reading-alerts/"
ALERT_GUIDE_LABEL = "How to read this alert"
