"""``dtk osi`` — Open Semantic Interchange interop (import / export / compile).

A self-contained, additive command group. It never runs the pipeline, takes no
lock, and touches no internal table:

- ``dtk osi import`` scaffolds a native detectkit metric from an OSI model metric
  (review the output, then commit it like any hand-written metric).
- ``dtk osi export`` publishes detectkit metrics into an OSI fragment (with the
  full config carried in ``custom_extensions[detectkit]``).
- ``dtk osi compile`` prints just the SQL an import would generate (for review).

Needs the optional ``[osi]`` extra (sqlglot) only for the ClickHouse target.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import click
import yaml


@click.group()
def osi() -> None:
    """Open Semantic Interchange (OSI) interop: import / export / compile metrics."""


def _split_csv(value: str | None) -> list[str] | None:
    if not value:
        return None
    items = [v.strip() for v in value.split(",") if v.strip()]
    return items or None


def _dump_metric_yaml(body: dict[str, Any], header: str) -> str:
    """Render a metric body as YAML with a ``#`` provenance header (mirrors config_emitter)."""
    text = yaml.safe_dump(body, sort_keys=False, allow_unicode=True, width=100)
    return header + text


def _import_header(result: Any, model_file: Path) -> str:
    lines = [
        "# Generated by `dtk osi import` — review before committing.",
        f"# Source OSI model: {model_file}",
        f"# Metric: {result.metric_name}  ·  target: {result.target}  ·  "
        f"sql-fingerprint: {result.fingerprint}",
        "# detectkit resumes from the last datapoint, so if you re-import and this",
        "# fingerprint changes, backfill/clean to avoid mixing definitions.",
    ]
    for w in result.warnings:
        lines.append(f"# NOTE: {w}")
    return "\n".join(lines) + "\n"


@osi.command(name="import")
@click.argument("model_file", type=click.Path(exists=True, dir_okay=False, path_type=Path))
@click.option("--metric", "-m", required=True, help="OSI metric name to import")
@click.option("--interval", "-i", required=True, help="Series grain (e.g. 1h, 10min, 3600)")
@click.option(
    "--target",
    type=click.Choice(["clickhouse", "cube"]),
    default="clickhouse",
    show_default=True,
    help="clickhouse = direct SQL from dataset.source; cube = Cube SQL-API (MEASURE)",
)
@click.option("--dataset", help="OSI dataset to build FROM (default: the model's only dataset)")
@click.option("--time-field", help="Time grain column / dimension (default: a field with is_time)")
@click.option("--where", help="Extra SQL predicate (ANSI) added to the WHERE clause")
@click.option("--cube", help="Cube name (cube target)")
@click.option("--cube-measure", help="Cube measure name (cube target; default: the metric name)")
@click.option("--time-dimension", help="Cube time dimension (cube target)")
@click.option("--seasonality", help="Comma-separated time-derived seasonality columns")
@click.option("--detector", default="mad", show_default=True, help="Starter detector type")
@click.option(
    "--out",
    "-o",
    type=click.Path(path_type=Path),
    help="Write the metric YAML here (a dir → <name>.yml). Default: print to stdout.",
)
@click.option("--force", is_flag=True, help="Overwrite an existing --out file")
def import_(
    model_file: Path,
    metric: str,
    interval: str,
    target: str,
    dataset: str | None,
    time_field: str | None,
    where: str | None,
    cube: str | None,
    cube_measure: str | None,
    time_dimension: str | None,
    seasonality: str | None,
    detector: str,
    out: Path | None,
    force: bool,
) -> None:
    """Scaffold a native detectkit metric from an OSI MODEL_FILE metric."""
    from detectkit.semantic import OsiError, import_osi_metric, load_osi_models

    try:
        models = load_osi_models(model_file)
        result = import_osi_metric(
            models=models,
            metric_name=metric,
            interval=interval,
            target=target,
            dataset=dataset,
            time_field=time_field,
            where=where,
            cube=cube,
            cube_measure=cube_measure,
            time_dimension=time_dimension,
            seasonality=_split_csv(seasonality),
            detector_type=detector,
        )
    except OsiError as exc:
        raise click.ClickException(str(exc)) from exc

    rendered = _dump_metric_yaml(result.metric, _import_header(result, model_file))

    if out is None:
        click.echo(rendered)
        click.echo("# (printed only — pass --out to write a metric file)", err=True)
        return

    dest = out / f"{result.metric_name}.yml" if out.is_dir() else out
    if dest.exists() and not force:
        raise click.ClickException(f"{dest} exists — pass --force to overwrite")
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(rendered)
    click.echo(f"Wrote {dest}")
    for w in result.warnings:
        click.echo(f"  note: {w}")


@osi.command()
@click.argument("model_file", type=click.Path(exists=True, dir_okay=False, path_type=Path))
@click.option("--metric", "-m", required=True, help="OSI metric name")
@click.option("--interval", "-i", required=True, help="Series grain (e.g. 1h, 10min, 3600)")
@click.option("--target", type=click.Choice(["clickhouse", "cube"]), default="clickhouse")
@click.option("--dataset", help="OSI dataset to build FROM")
@click.option("--time-field", help="Time grain column / dimension")
@click.option("--where", help="Extra SQL predicate (ANSI)")
@click.option("--cube", help="Cube name (cube target)")
@click.option("--cube-measure", help="Cube measure name (cube target)")
@click.option("--time-dimension", help="Cube time dimension (cube target)")
def compile(  # noqa: A001 - mirrors the `dtk osi compile` verb
    model_file: Path,
    metric: str,
    interval: str,
    target: str,
    dataset: str | None,
    time_field: str | None,
    where: str | None,
    cube: str | None,
    cube_measure: str | None,
    time_dimension: str | None,
) -> None:
    """Print ONLY the SQL an import would generate (no file written)."""
    from detectkit.semantic import OsiError, import_osi_metric, load_osi_models

    try:
        models = load_osi_models(model_file)
        result = import_osi_metric(
            models=models,
            metric_name=metric,
            interval=interval,
            target=target,
            dataset=dataset,
            time_field=time_field,
            where=where,
            cube=cube,
            cube_measure=cube_measure,
            time_dimension=time_dimension,
        )
    except OsiError as exc:
        raise click.ClickException(str(exc)) from exc
    click.echo(result.sql)


@osi.command()
@click.option(
    "--select", "-s", "selector", help="Metric selector (name / path / tag:<t>); default: all"
)
@click.option("--model-name", default="detectkit_export", show_default=True, help="OSI model name")
@click.option(
    "--out",
    "-o",
    type=click.Path(path_type=Path),
    help="Write the OSI YAML here. Default: print to stdout.",
)
@click.option("--force", is_flag=True, help="Overwrite an existing --out file")
def export(selector: str | None, model_name: str, out: Path | None, force: bool) -> None:
    """Export native detectkit metrics into an OSI fragment (config in custom_extensions)."""
    from detectkit.cli.commands.run import find_project_root, select_metrics
    from detectkit.config.validator import validate_project_metrics
    from detectkit.semantic import export_models

    root = find_project_root()
    if root is None:
        raise click.ClickException(
            "not inside a detectkit project (no detectkit_project.yml found)"
        )

    try:
        pairs = select_metrics(selector, root) if selector else validate_project_metrics(root)
    except Exception as exc:
        raise click.ClickException(str(exc)) from exc
    configs = [cfg for _, cfg in pairs]
    if not configs:
        raise click.ClickException("no metrics selected")

    doc = export_models(configs, model_name=model_name)
    rendered = yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=100)
    header = (
        f"# Generated by `dtk osi export` — {len(configs)} metric(s).\n"
        "# The portable measure is a placeholder; the exact detectkit definition\n"
        "# (detectors, alerting, query) rides in custom_extensions[detectkit].\n"
    )
    rendered = header + rendered

    if out is None:
        click.echo(rendered)
        return
    if out.exists() and not force:
        raise click.ClickException(f"{out} exists — pass --force to overwrite")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(rendered)
    click.echo(f"Wrote {out} ({len(configs)} metric(s))", err=False)


def run_osi() -> None:
    """Entry shim (kept symmetric with other commands; the group is wired in main)."""
    osi(standalone_mode=True)  # pragma: no cover
    sys.exit(0)  # pragma: no cover
